#!/usr/bin/env python3
"""
tools/stress/sync_registries.py

Phase N1 (S130 extension). Авто-синкронизация на STRESS_SCENARIOS.md
от JSON сценариите в `tools/stress/scenarios/`.

CRITICAL: поправя 2-та skipped patches от STRESS_HANDOFF_20260508.md
които изискваха manual update на регистъра след всеки нов сценарий.

Стратегия: Open-ended append.
  - Manual content в STRESS_SCENARIOS.md се ЗАПАЗВА непокътнато.
  - Auto-generated регистър седи в края, между маркери:

    <!-- STRESS-REGISTRY-AUTO:start (do not edit between these markers) -->
    ...автоматично съдържание (S013+ scenarios)...
    <!-- STRESS-REGISTRY-AUTO:end -->

  - При първи run, маркерите се добавят в края.
  - При следващ run, съдържанието вътре се преписва, маркерите остават.

Режими:
  --check    CI-friendly: exit 1 ако генерираното съдържание != текущото
             (използва се в .github/workflows/stress-registry-check.yml).
  --update   Прилага промените (записва файла).
  --dry-run  Печата diff, не пише (default).

Usage:
    python3 sync_registries.py
    python3 sync_registries.py --update
    python3 sync_registries.py --check
"""

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCENARIOS_DIR = REPO_ROOT / "tools" / "stress" / "scenarios"
REGISTRY_MD = REPO_ROOT / "STRESS_SCENARIOS.md"

MARK_START = "<!-- STRESS-REGISTRY-AUTO:start (do not edit between these markers) -->"
MARK_END = "<!-- STRESS-REGISTRY-AUTO:end -->"

# Сценарии, които вече са документирани ръчно в горната част на
# STRESS_SCENARIOS.md (S001-S012). Auto-секцията започва от S013+.
MANUAL_SCENARIO_IDS = {f"S{n:03d}" for n in range(1, 13)}


def load_scenarios() -> list[dict]:
    """Зарежда всички scenarios/*.json sorted by id."""
    if not SCENARIOS_DIR.exists():
        return []
    out = []
    for path in sorted(SCENARIOS_DIR.glob("S*.json")):
        try:
            with open(path) as f:
                data = json.load(f)
            data["_path"] = str(path.relative_to(REPO_ROOT))
            out.append(data)
        except Exception as e:
            print(f"[WARN] {path}: {e}", file=sys.stderr)
    return sorted(out, key=lambda s: s.get("id", ""))


def render_scenario(s: dict) -> str:
    """Превръща един scenario JSON в markdown ред."""
    sid = s.get("id", "?")
    name = s.get("name", "(без име)")
    cat = s.get("category", "—")
    pri = s.get("priority", "—")
    status = s.get("status", "—")
    module = s.get("linked_module", "—")
    added = s.get("added_date", "—")
    fail = s.get("fail_means", "—")

    actions = s.get("action_steps") or []
    expected = s.get("expected_result") or []

    lines = [
        f"### {sid} — {name}",
        "",
        f"- **Дата добавен:** {added}",
        f"- **Свързан с:** {module}",
        f"- **Категория:** {cat}",
        f"- **Приоритет:** {pri}",
        f"- **Статус:** {status}",
        f"- **Source:** `{s.get('_path', '?')}`",
    ]
    if s.get("precondition"):
        lines.append(f"- **Precondition:** {s['precondition']}")
    if actions:
        lines.append("- **Action:**")
        for i, a in enumerate(actions, 1):
            lines.append(f"  {i}. {a}")
    if expected:
        lines.append("- **Expected result:**")
        for e in expected:
            lines.append(f"  - {e}")
    if s.get("smoke_sql"):
        lines.append(f"- **Smoke SQL:** `{s['smoke_sql'][:160]}{'…' if len(s['smoke_sql']) > 160 else ''}`")
        lines.append(f"- **Expects ≥:** {s.get('expects_at_least', 0)} rows")
    if fail and fail != "—":
        lines.append(f"- **Fail означава:** {fail}")
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def render_auto_section(scenarios: list[dict]) -> str:
    """Генерира пълното съдържание между маркерите."""
    auto_scenarios = [s for s in scenarios
                      if s.get("id") not in MANUAL_SCENARIO_IDS]
    by_cat: dict[str, list[dict]] = {}
    for s in auto_scenarios:
        cat = s.get("category", "uncategorized")
        by_cat.setdefault(cat, []).append(s)

    parts = [
        "",
        "## 🤖 АВТО-РЕГИСТЪР (S013+) — генериран от sync_registries.py",
        "",
        f"**Източник:** `tools/stress/scenarios/*.json` "
        f"({len(auto_scenarios)} сценария).  ",
        "**Не редактирай ръчно** между маркерите — следващото пускане на "
        "`sync_registries.py --update` ще презапише.",
        "",
        f"### Обобщение",
        "",
        f"- Общ брой: **{len(scenarios)}** ({len(MANUAL_SCENARIO_IDS & {s.get('id', '') for s in scenarios})} manual + {len(auto_scenarios)} auto)",
        f"- Категории: {len(by_cat)}",
        f"- Generated by: `tools/stress/sync_registries.py`",
        "",
    ]

    if by_cat:
        parts.append("### Бройка по категории")
        parts.append("")
        parts.append("| Категория | Брой |")
        parts.append("|---|---|")
        for cat in sorted(by_cat.keys()):
            parts.append(f"| {cat} | {len(by_cat[cat])} |")
        parts.append("")

    parts.append("### Сценарии (групирани по категория)")
    parts.append("")
    for cat in sorted(by_cat.keys()):
        parts.append(f"#### Категория: {cat}")
        parts.append("")
        for s in sorted(by_cat[cat], key=lambda x: x.get("id", "")):
            parts.append(render_scenario(s))
    return "\n".join(parts)


def replace_or_append(content: str, auto_block: str) -> str:
    """Заменя auto секцията между маркерите. Append-ва ако липсват."""
    if MARK_START in content and MARK_END in content:
        before = content.split(MARK_START)[0]
        after = content.split(MARK_END, 1)[1]
        return f"{before}{MARK_START}\n{auto_block}\n{MARK_END}{after}"
    sep = "\n\n" if not content.endswith("\n\n") else ""
    return f"{content.rstrip()}\n\n{MARK_START}\n{auto_block}\n{MARK_END}\n"


def show_diff(old: str, new: str) -> None:
    diff = difflib.unified_diff(
        old.splitlines(keepends=True),
        new.splitlines(keepends=True),
        fromfile="STRESS_SCENARIOS.md (current)",
        tofile="STRESS_SCENARIOS.md (after sync)",
        n=2,
    )
    sys.stdout.writelines(diff)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--update", action="store_true",
                    help="Запиши промените в STRESS_SCENARIOS.md.")
    ap.add_argument("--check", action="store_true",
                    help="CI mode: exit 1 ако auto секцията не е up-to-date.")
    ap.add_argument("--dry-run", action="store_true", default=True,
                    help="(default) print diff, no write.")
    args = ap.parse_args()

    scenarios = load_scenarios()
    print(f"[INFO] Заредени {len(scenarios)} сценария от {SCENARIOS_DIR}",
          file=sys.stderr)

    if not REGISTRY_MD.exists():
        print(f"[FATAL] {REGISTRY_MD} липсва", file=sys.stderr)
        return 2

    current = REGISTRY_MD.read_text(encoding="utf-8")
    auto_block = render_auto_section(scenarios)
    new = replace_or_append(current, auto_block)

    if current == new:
        print(f"[OK] {REGISTRY_MD.name} вече е up-to-date "
              f"({len(scenarios)} сценария).")
        return 0

    if args.check:
        print(f"[FAIL] {REGISTRY_MD.name} НЕ е up-to-date — пусни "
              f"`python3 tools/stress/sync_registries.py --update`",
              file=sys.stderr)
        show_diff(current, new)
        return 1

    if args.update:
        REGISTRY_MD.write_text(new, encoding="utf-8")
        print(f"[OK] {REGISTRY_MD.name} обновен — {len(scenarios)} сценария "
              f"({len(scenarios) - len([s for s in scenarios if s.get('id') in MANUAL_SCENARIO_IDS])} auto).")
        return 0

    show_diff(current, new)
    print(f"\n[DRY-RUN] За запис: --update", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
